### ISSUE TITLE
予測型「戻る」ジェスチャーが機能しない

### ISSUE THREAD

**Issue by kosenda** [kosenda/PeriodSinceBirth#1]
初期画面がローディング画面でDataStoreからデータを読み込んだ後に画面遷移するが、
その後に戻るジェスチャーをするとローディング画面のLaunchedEffect内で行なっているデータの
読み込み処理をしないためにローディング画面のまま止まってしまう。
そのために、ローディング画面に戻れないようにするために
以下のコードをローディング画面の遷移先に追加したことで機能しなくなった。
```
BackHandler(true) {} 
```

**Comment by georgeh1998** [comment]
説明が長くなりそうだったため、Twitterではなくこちらにコメントさせていただきます！
(※解決策は他にもあると思いますので参考までに。。)

下記は削除した前提で説明を進めます。
```kotlin
BackHandler(true) {}
```

まず下記ですが、
> LaunchedEffect内で行なっているデータの読み込み処理をしないためにローディング画面のまま止まってしまう。

これは `LoadingScreen`の`dispatch(AppAction.FetchBirthday)`が何も状態を変更していないためだと思います。
LaunchedEffect自体は呼ばれています。

```kotlin
@Composable
fun LoadingScreen() {
    val dispatch = rememberDispatcher()
    LaunchedEffect(Unit) {
        dispatch(AppAction.FetchBirthday)
    }
   ...
```


`dispatch(AppAction.FetchBirthday)`を呼ぶと、以下の`Middleware`が呼ばれると思います。

初回起動でLoading画面に入った場合は、★1と★2の処理により、状態(state)が更新されるので、画面遷移が発生します。
一方で、戻るボタンなどでLoading画面に入った場合、★1と★2は呼ばれますが、状態が更新されません。
(正確に説明すると、更新自体は行っても前の状態と変わらないので、Reduxの状態が内部では実質的に更新されません)

```kotlin
// ※見やすいように色々省略
class AppMiddleware (
) : Middleware<AppState> {
    override fun invoke(): (next: Dispatcher) -> (action: Any) -> Any = { next ->
            is AppAction.FetchBirthday -> {
                    when {
                        birthday != null -> {
                            next(AppAction.ChangeBirthday(ZonedDateTime.parse(birthday)))     ★1
                            next(AppAction.TransitionScreen(NavigationItems.PeriodSinceBirth))  ★2
                    }
            }
}
```

つまり戻るボタンでLoading画面に戻った場合、Redulxの状態(NavigationItem)にも、Loading画面に戻ったことを伝えなければならないと思い餡巣。
以上から、以下のような解決策があると思います！
解決策は急いで考えたので、どういう画面遷移でアプリを作っていくかによっては、もっと良い方法があると思います...

## 解決策1

```kotlin
@Composable
fun LoadingScreen() {
    val dispatch = rememberDispatcher()
    LaunchedEffect(Unit) {
        dispatch(AppAction.TransitionScreen(NavigationItems.Loading)) // これを追加！！！
        dispatch(AppAction.FetchBirthday)
    }
```

## 解決策2
※書いていて思いましたが、解決策1の方が良いと思います。この画面から戻る場合、必ずLoading画面に戻るとは限らないからです。動作を把握するという意味では良いかもしれません。
```kotlin
@Composable
fun PeriodSinceBirthScreen(birthday: ZonedDateTime) {
   BackHandler(true) {
        dispatch(AppAction.TransitionScreen(NavigationItems.Loading)) // これを追加
    }
    ...
}
```

**Comment by kosenda** [comment]
いただいた解決策でソースの修正を行いました。
d243860
しかし、PeriodSinceBirthScreenで連続して戻るジェスチャーを行うとLoadingのままになってしまうことに気がつきました。
ですので、Loading画面は廃止しPeriodSinceBirthScreen画面のLaunched内でDataStoreの読み込み処理を行うことで、Loadingのままになることを防ごうと考えています。

**Comment by kosenda** [comment]
再度修正を行いました。
554bae6

修正内容は以下になります。
- Loading画面を廃止
- PeriodSinceBirth画面で引数のbirthdayの状態によってLoadingか元々のPeriodSinceBirthで表示していたコンテンツを切り替えるように変更
- ルート画面をLoading画面からPeriodSinceBirth画面に変更
- Previewの追加
- InputBirthday画面は初期入力する場合と変更する場合で引数にBoolean値であるisInitialを分けて渡しているが、isInitialがtrueのとき（初期入力時）は一つ前のコメントで消したソースを戻して以下のようなソースを追加
```
BackHandler(isInitial) {} // 初期時のみ、戻るジェスチャーを無効にする
```

InputBirthday画面の初期入力時で戻るジェスチャーを無効にしたのは、Loading画面に遷移してDataStoreを読み込んでも結局元の画面に戻るのみかつ、アプリをインストールした最初のタイミングのみ無効であるため戻るジェスチャーは不要であると考えたためです。

**Comment by kosenda** [comment]
### クローズした上記で追加修正を行いました。
 222bb01
- InputBirthday画面の初期入力時の戻るジェスチャーを無効にしたことで、Loading画面に到達するのはアプリの起動時のみとなったため、PeriodSinceBirthScreenのLaunchedEffect内に追加していたソース```dispatch(AppAction.TransitionScreen(NavigationItems.PeriodSinceBirth))```
を削除しました。

**Comment by georgeh1998** [comment]
@kosenda 

しばらく確認できておらずすみません、、、
ひとまず、修正できてよかたです！
こちらもkotlinreduxの勉強ができてよかったです
